ldap: 
   container_name: ldap 
   restart: always 
   #build: ../images/docker-ldap/ 
   image: accenture/adop-ldap:0.1.3 
   net: ${CUSTOM_NETWORK_NAME} 
   expose:
     - "389"
   ports:
     - "389/tcp:389/tcp" 
   environment: 
     INITIAL_ADMIN_USER: ${INITIAL_ADMIN_USER} 
     INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD} 
     SLAPD_PASSWORD: ${LDAP_PWD} 
     SLAPD_DOMAIN: ${LDAP_DOMAIN} 
     SLAPD_FULL_DOMAIN: ${LDAP_FULL_DOMAIN} 


ldap-ltb:
  container_name: ldap-ltb
  restart: always
  image: accenture/adop-ldap-ltb:0.1.0
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "80"
  ports: 
    - "443:80/tcp"   
  environment:
    LDAP_LTB_URL: "ldap://${LDAP_SERVER}"
    LDAP_LTB_DN: "${LDAP_ADMIN},${LDAP_FULL_DOMAIN}"
    LDAP_LTB_PWD: "${LDAP_PWD}"
    LDAP_LTB_BS: "${LDAP_FULL_DOMAIN}"

ldap-phpadmin:
  container_name: ldap-phpadmin
  restart: always
  image: accenture/adop-ldap-phpadmin:0.1.0
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "80"
  ports: 
    - "80:80/tcp"
  environment:
    LDAP_SERVER_NAME: "LDAP"
    LDAP_SERVER_HOST: "ldap"
    LDAP_SERVER_PORT: "389"
    LDAP_SERVER_BIND_ID: "${LDAP_ADMIN},${LDAP_FULL_DOMAIN}"
    LDAP_SERVER_BASE_DN: "${LDAP_FULL_DOMAIN}"

